name: Type Checking
on: [push]
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: phijor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Getting nix version
        run: nix --version
      - name: Type checking the library
        run: nix build --print-build-logs '.#multiset'
