name: Type Checking
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: phijor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Getting nix version
        run: nix --version
      - name: Type checking the library
        run: nix build --print-build-logs '.#multiset'
      - name: Render Agda code to HTML
        run: nix build --print-build-logs '.#multiset.html'
      # XXX: https://github.com/actions/deploy-pages/issues/58
      - name: "Fix permissions on build output"
        run: |
          cp --recursive --dereference --no-preserve=mode,ownership result-html public
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    name: "Deploy rendered Agda code to Pages"
    if: success() && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
